version: "3.8"

name: rabbitmq-cluster
services:
    rabbitmq1:
        build: rabbitmq/.
        container_name: rabbitmq1
        # ports:
        #     - 5672:5672
        #     - 15673:15672
        volumes:
            - "./data1:/var/lib/rabbitmq/mnesia/"
            - ./rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
            - ./rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
        hostname: "rabbitmq1"
        environment:
            - RABBITMQ_ERLANG_COOKIE='12345'
            - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
        entrypoint: /usr/local/bin/cluster-entrypoint.sh
        networks: 
            - rabbitmq-cluster-network
    rabbitmq2:
        build: rabbitmq/.
        container_name: rabbitmq2
        environment:
            - JOIN_CLUSTER_HOST=rabbitmq1
            - RABBITMQ_ERLANG_COOKIE='12345'
            - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
        depends_on:
          - rabbitmq1
        volumes:
            - "./data2:/var/lib/rabbitmq/mnesia/"
            - ./rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
            - ./rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
        hostname: "rabbitmq2"
        entrypoint: /usr/local/bin/cluster-entrypoint.sh
        networks: 
            - rabbitmq-cluster-network
    rabbitmq3:
        build: rabbitmq/.
        container_name: rabbitmq3
        # ports:
        #     - 5675:5672
        #     - 15675:15672
        depends_on:
          - rabbitmq1
          - rabbitmq2
        environment:
          - JOIN_CLUSTER_HOST=rabbitmq1
          - RABBITMQ_ERLANG_COOKIE='12345'
          - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
        volumes:
          - "./data3:/var/lib/rabbitmq/mnesia/"
          - ./rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
          - ./rabbitmq/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
        hostname: "rabbitmq3"
        entrypoint: /usr/local/bin/cluster-entrypoint.sh
        networks: 
            - cluster-network
    haproxy:
        image: haproxy:1.9
        container_name: haproxy
        volumes:
          - ./haproxy:/usr/local/etc/haproxy/
        depends_on:
          - rabbitmq1
          - rabbitmq2
          - rabbitmq3
        ports:
          - 15672:15672
          - 5672:5672
        networks: 
            - rabbitmq-cluster-network
networks:
    rabbitmq-cluster-network:
     driver: bridge

